### ISSUE TITLE
Compilation error (No such file or directory)

### ISSUE THREAD

**Issue by Kravantokh** [meutzitzu/termos#3]
When the repo is freshly cloned it does not have a *bin* directory and gcc won't create it on its own showing the message:
`/usr/bin/ld: cannot open output file bin/termos: No such file or directory`
The moment I create this folder it compiles. 

Thus I would recommend creating the bin directory with a *README* file in it stating why it exists or adding a *.gitignore* with the following lines:
```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```

I think the latter solution is more elegant, but either one should work.

You could  also add the creation of such a folder to the compile script suggested in issue #2 but that would be an unnecessary hack and thus should not be the way to resolve this issue.

**Comment by meutzitzu** [comment]
# Fixed in dd8a15671878b584614e40175c05640865e71a5d

ended up using `mkdir -p` inside `./compile.sh`

as GLaDOS once said: ***The best solution to a problem is usually the easiest one***
